# Generated by Django 3.2 on 2021-05-06 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 14, 33, 33, 692502, tzinfo=utc), editable=False, verbose_name='start date'),
        ),
        migrations.CreateModel(
            name='AnswerChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questions')),
            ],
        ),
    ]
