# Generated by Django 3.2 on 2021-05-06 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210506_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 14, 35, 48, 135373, tzinfo=utc), editable=False, verbose_name='start date'),
        ),
    ]
