# Generated by Django 3.2 on 2021-05-06 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveys_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 15, 40, 21, 694506, tzinfo=utc), editable=False, verbose_name='start date'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32)),
                ('u_answers', models.ManyToManyField(to='surveys.AnswerChoices')),
            ],
        ),
    ]
